name: oukso
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.1.2 
  flex_color_scheme: ^7.3.1
  flutter_svg: ^2.0.10+1  
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  provider: ^6.1.2
  socket_io_client: ^1.0.2
  emoji_picker_flutter: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true 
  image_path: assets/Logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/