// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrGpLds3N1d0TjCKVBbxnu2ON5LXgLsnA',
    appId: '1:754321391897:web:6fe1c8a368ed4854ebc588',
    messagingSenderId: '754321391897',
    projectId: 'oukso-efaf3',
    authDomain: 'oukso-efaf3.firebaseapp.com',
    storageBucket: 'oukso-efaf3.appspot.com',
    measurementId: 'G-619T4ZD2NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI3oR7QkID5DRanxetSJh_VFwyDEsIxtk',
    appId: '1:754321391897:android:bd78be52271bdc93ebc588',
    messagingSenderId: '754321391897',
    projectId: 'oukso-efaf3',
    storageBucket: 'oukso-efaf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtJnqWQ76Th43TdnaZVwi318oftymCops',
    appId: '1:754321391897:ios:36486e08dc3dbf41ebc588',
    messagingSenderId: '754321391897',
    projectId: 'oukso-efaf3',
    storageBucket: 'oukso-efaf3.appspot.com',
    iosBundleId: 'com.example.oukso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtJnqWQ76Th43TdnaZVwi318oftymCops',
    appId: '1:754321391897:ios:36486e08dc3dbf41ebc588',
    messagingSenderId: '754321391897',
    projectId: 'oukso-efaf3',
    storageBucket: 'oukso-efaf3.appspot.com',
    iosBundleId: 'com.example.oukso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrGpLds3N1d0TjCKVBbxnu2ON5LXgLsnA',
    appId: '1:754321391897:web:84ff9f0eec47df83ebc588',
    messagingSenderId: '754321391897',
    projectId: 'oukso-efaf3',
    authDomain: 'oukso-efaf3.firebaseapp.com',
    storageBucket: 'oukso-efaf3.appspot.com',
    measurementId: 'G-BS2CNB4ZQM',
  );
}
